package com.model;


/**
 * TRuku generated by MyEclipse Persistence Tools
 */

public class TRuku implements java.io.Serializable
{

	// Fields

	private Integer id;
	private Integer goods_id;
	private String danjuhao;
	
	private Integer rukushu;
	private String rukushi;
	private String beizhu;
	
	private TGoods goods;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getGoods_id() {
		return goods_id;
	}

	public void setGoods_id(Integer goods_id) {
		this.goods_id = goods_id;
	}

	public String getDanjuhao() {
		return danjuhao;
	}

	public void setDanjuhao(String danjuhao) {
		this.danjuhao = danjuhao;
	}

	public Integer getRukushu() {
		return rukushu;
	}

	public void setRukushu(Integer rukushu) {
		this.rukushu = rukushu;
	}

	public String getRukushi() {
		return rukushi;
	}

	public void setRukushi(String rukushi) {
		this.rukushi = rukushi;
	}

	public String getBeizhu() {
		return beizhu;
	}

	public void setBeizhu(String beizhu) {
		this.beizhu = beizhu;
	}

	public TGoods getGoods() {
		return goods;
	}

	public void setGoods(TGoods goods) {
		this.goods = goods;
	}

}